### ISSUE TITLE
Not possible to specify an opcode directly in hex

### ISSUE THREAD

**Issue by vyzo** [quilt/etk#110] opened 2022-09-10 08:39 UTC
I would like to be able to test extension opcodes, that are otherwise invalid, using the assembler.
Unfortunately the parser does not seem to provide any escape mechanism for directly embedding opcodes in the program.

For example, say that I am defining in my EVM impl semantics for the `0xb0` opcode,
I would like to be able to just assemble a program that says `0xb0` or `ins(0xb0)`, but the parser fails me.

**Comment by vyzo** [comment] 2022-09-10 09:57
Note that the request here is a generic way to specify arbitrary opcodes in the assembled program. 
A builtin macro like `ins(0xXX)` or just `hex(0xXX)` will do!

**Comment by SamWilsn** [comment] 2022-10-18 03:42
Thanks for reporting!

Duplicate of: https://github.com/quilt/etk/issues/106

**Closed by SamWilsn** 2022-10-18 03:42 UTC
